presets:
  workstation: [base, shell, syncthing, dev-c, dev-python, dev-node]
  server: [base, shell, syncthing, dev-python, dev-node]

hosts:
  everest:
    preset: workstation
    user: blank
  campbell:
    preset: server
    user: blank
  granite:
    preset: workstation
    extra: [apps-docker]
    user: blank
