presets:
  workstation: [base, shell, syncthing, dev-c, dev-python, dev-node]
  server: [base, shell, syncthing, dev-python, dev-node]
  hpc: [shell-hpc]

hosts:
  everest:
    preset: workstation
    user: blank
  campbell:
    preset: server
    user: blank
  granite:
    preset: workstation
    extra: [apps-docker]
    user: blank
  pioneer:
    preset: hpc
    user: axj770
    aliases: [hpc5, hpc6, hpc7, hpc8, hpctransfer1]
    hpc:
      scratch: /scratch/pioneer/users/axj770
      lmod_pkg: /usr/local/lmod/lmod
      modules: [GCCcore/13.2.0, git/2.42.0-GCCcore-13.2.0, Python/3.11.5-GCCcore-13.2.0]
