# --------
# Global
# --------
add_newline = true

format = """
$hostname$directory
$character
"""

# --------
# Directory
# --------
[directory]
truncate_to_repo = true
truncation_length = 3
style = "bold blue"

# --------
# Hostname
# --------
[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "dimmed red"

# --------
# Prompt symbol
# --------
[character]
success_symbol = "[❯](bold green)"
error_symbol   = "[❯](bold red)"